/**
 * Turns the raw JPEGs in /portofolio into the responsive WebP set the site
 * ships, plus src/data/generated/images.ts (dimensions + LQIP placeholders).
 *
 * Run with: npm run images
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { projectImages, WIDTHS } from "./image-manifest.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "portofolio");
const OUT = path.join(ROOT, "public", "projects");
const DATA = path.join(ROOT, "src", "data", "generated");

const sourceCache = new Map();
async function sourceFiles(type) {
  if (!sourceCache.has(type)) {
    const files = (await readdir(path.join(SRC, type))).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort();
    sourceCache.set(type, files);
  }
  return sourceCache.get(type);
}

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(DATA, { recursive: true });

  /** @type {Record<string, {w:number,h:number,blur:string}>} */
  const meta = {};
  let count = 0;

  for (const { slug, picks } of projectImages) {
    const dir = path.join(OUT, slug);
    await mkdir(dir, { recursive: true });

    const sources = [];
    for (const [type, indexes] of picks) {
      const files = await sourceFiles(type);
      for (const i of indexes) {
        if (!files[i]) throw new Error(`${slug}: ${type}[${i}] does not exist (folder has ${files.length} files)`);
        sources.push(path.join(SRC, type, files[i]));
      }
    }

    for (const [i, file] of sources.entries()) {
      const name = i === 0 ? "cover" : String(i).padStart(2, "0");
      const key = `/projects/${slug}/${name}`;
      const image = sharp(file).rotate();
      const { width, height } = await image.metadata();

      for (const w of WIDTHS) {
        const target = Math.min(w, width);
        await image
          .clone()
          .resize({ width: target, withoutEnlargement: true })
          .webp({ quality: w >= 1200 ? 76 : 80, effort: 5 })
          .toFile(path.join(dir, `${name}-${w}.webp`));
      }

      const blur = await image.clone().resize({ width: 16 }).webp({ quality: 28 }).toBuffer();
      meta[key] = { w: width, h: height, blur: `data:image/webp;base64,${blur.toString("base64")}` };
      count++;
    }
    console.log(`${slug.padEnd(30)} ${sources.length} images`);
  }

  const body = `// AUTO-GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run \`npm run images\` after changing scripts/image-manifest.mjs.

export type ImageMeta = { w: number; h: number; blur: string };

export const imageMeta: Record<string, ImageMeta> = ${JSON.stringify(meta, null, 2)};

export const imageWidths = ${JSON.stringify(WIDTHS)} as const;
`;
  await writeFile(path.join(DATA, "images.ts"), body, "utf8");
  console.log(`\n${count} images → ${count * WIDTHS.length} webp files`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
